name = "fm5-production"
main = ".output/server/index.mjs"
compatibility_date = "2025-09-24"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"

[observability]
enabled = true

[vars]
NODE_ENV = "production"
APP_ENV = "production"

[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "fm5-production-files"
