/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authProductsIndexRouteImport } from './routes/(auth)/products/index'
import { Route as authModelsIndexRouteImport } from './routes/(auth)/models/index'
import { Route as authInventoryIndexRouteImport } from './routes/(auth)/inventory/index'
import { Route as authFilamentsIndexRouteImport } from './routes/(auth)/filaments/index'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authProductsIndexRoute = authProductsIndexRouteImport.update({
  id: '/(auth)/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const authModelsIndexRoute = authModelsIndexRouteImport.update({
  id: '/(auth)/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const authInventoryIndexRoute = authInventoryIndexRouteImport.update({
  id: '/(auth)/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const authFilamentsIndexRoute = authFilamentsIndexRouteImport.update({
  id: '/(auth)/filaments/',
  path: '/filaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/filaments': typeof authFilamentsIndexRoute
  '/inventory': typeof authInventoryIndexRoute
  '/models': typeof authModelsIndexRoute
  '/products': typeof authProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/filaments': typeof authFilamentsIndexRoute
  '/inventory': typeof authInventoryIndexRoute
  '/models': typeof authModelsIndexRoute
  '/products': typeof authProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(auth)/filaments/': typeof authFilamentsIndexRoute
  '/(auth)/inventory/': typeof authInventoryIndexRoute
  '/(auth)/models/': typeof authModelsIndexRoute
  '/(auth)/products/': typeof authProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/filaments'
    | '/inventory'
    | '/models'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/filaments' | '/inventory' | '/models' | '/products'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(auth)/filaments/'
    | '/(auth)/inventory/'
    | '/(auth)/models/'
    | '/(auth)/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  authFilamentsIndexRoute: typeof authFilamentsIndexRoute
  authInventoryIndexRoute: typeof authInventoryIndexRoute
  authModelsIndexRoute: typeof authModelsIndexRoute
  authProductsIndexRoute: typeof authProductsIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/products/': {
      id: '/(auth)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof authProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/models/': {
      id: '/(auth)/models/'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof authModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/inventory/': {
      id: '/(auth)/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof authInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/filaments/': {
      id: '/(auth)/filaments/'
      path: '/filaments'
      fullPath: '/filaments'
      preLoaderRoute: typeof authFilamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  authFilamentsIndexRoute: authFilamentsIndexRoute,
  authInventoryIndexRoute: authInventoryIndexRoute,
  authModelsIndexRoute: authModelsIndexRoute,
  authProductsIndexRoute: authProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
