/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FilamentsRouteImport } from './routes/filaments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authProductsNewRouteImport } from './routes/(auth)/products/new'
import { Route as authProductsProductIdRouteImport } from './routes/(auth)/products/$productId'
import { Route as authModelsModelIdRouteImport } from './routes/(auth)/models/$modelId'
import { Route as authInventoryItemRouteImport } from './routes/(auth)/inventory/$item'
import { Route as authFilamentsFilamentIdRouteImport } from './routes/(auth)/filaments/$filamentId'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FilamentsRoute = FilamentsRouteImport.update({
  id: '/filaments',
  path: '/filaments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authProductsNewRoute = authProductsNewRouteImport.update({
  id: '/(auth)/products/new',
  path: '/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const authProductsProductIdRoute = authProductsProductIdRouteImport.update({
  id: '/(auth)/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const authModelsModelIdRoute = authModelsModelIdRouteImport.update({
  id: '/(auth)/models/$modelId',
  path: '/models/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const authInventoryItemRoute = authInventoryItemRouteImport.update({
  id: '/(auth)/inventory/$item',
  path: '/inventory/$item',
  getParentRoute: () => rootRouteImport,
} as any)
const authFilamentsFilamentIdRoute = authFilamentsFilamentIdRouteImport.update({
  id: '/(auth)/filaments/$filamentId',
  path: '/filaments/$filamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/filaments': typeof FilamentsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/products': typeof ProductsRoute
  '/filaments/$filamentId': typeof authFilamentsFilamentIdRoute
  '/inventory/$item': typeof authInventoryItemRoute
  '/models/$modelId': typeof authModelsModelIdRoute
  '/products/$productId': typeof authProductsProductIdRoute
  '/products/new': typeof authProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/filaments': typeof FilamentsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/products': typeof ProductsRoute
  '/filaments/$filamentId': typeof authFilamentsFilamentIdRoute
  '/inventory/$item': typeof authInventoryItemRoute
  '/models/$modelId': typeof authModelsModelIdRoute
  '/products/$productId': typeof authProductsProductIdRoute
  '/products/new': typeof authProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/filaments': typeof FilamentsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/products': typeof ProductsRoute
  '/(auth)/filaments/$filamentId': typeof authFilamentsFilamentIdRoute
  '/(auth)/inventory/$item': typeof authInventoryItemRoute
  '/(auth)/models/$modelId': typeof authModelsModelIdRoute
  '/(auth)/products/$productId': typeof authProductsProductIdRoute
  '/(auth)/products/new': typeof authProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/filaments'
    | '/inventory'
    | '/login'
    | '/models'
    | '/products'
    | '/filaments/$filamentId'
    | '/inventory/$item'
    | '/models/$modelId'
    | '/products/$productId'
    | '/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/filaments'
    | '/inventory'
    | '/login'
    | '/models'
    | '/products'
    | '/filaments/$filamentId'
    | '/inventory/$item'
    | '/models/$modelId'
    | '/products/$productId'
    | '/products/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/filaments'
    | '/inventory'
    | '/login'
    | '/models'
    | '/products'
    | '/(auth)/filaments/$filamentId'
    | '/(auth)/inventory/$item'
    | '/(auth)/models/$modelId'
    | '/(auth)/products/$productId'
    | '/(auth)/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FilamentsRoute: typeof FilamentsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  ProductsRoute: typeof ProductsRoute
  authFilamentsFilamentIdRoute: typeof authFilamentsFilamentIdRoute
  authInventoryItemRoute: typeof authInventoryItemRoute
  authModelsModelIdRoute: typeof authModelsModelIdRoute
  authProductsProductIdRoute: typeof authProductsProductIdRoute
  authProductsNewRoute: typeof authProductsNewRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filaments': {
      id: '/filaments'
      path: '/filaments'
      fullPath: '/filaments'
      preLoaderRoute: typeof FilamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/products/new': {
      id: '/(auth)/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof authProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/products/$productId': {
      id: '/(auth)/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof authProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/models/$modelId': {
      id: '/(auth)/models/$modelId'
      path: '/models/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof authModelsModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/inventory/$item': {
      id: '/(auth)/inventory/$item'
      path: '/inventory/$item'
      fullPath: '/inventory/$item'
      preLoaderRoute: typeof authInventoryItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/filaments/$filamentId': {
      id: '/(auth)/filaments/$filamentId'
      path: '/filaments/$filamentId'
      fullPath: '/filaments/$filamentId'
      preLoaderRoute: typeof authFilamentsFilamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FilamentsRoute: FilamentsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  ProductsRoute: ProductsRoute,
  authFilamentsFilamentIdRoute: authFilamentsFilamentIdRoute,
  authInventoryItemRoute: authInventoryItemRoute,
  authModelsModelIdRoute: authModelsModelIdRoute,
  authProductsProductIdRoute: authProductsProductIdRoute,
  authProductsNewRoute: authProductsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
