/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as FilamentsIndexRouteImport } from './routes/filaments/index'
import { ServerRoute as ApiSlicedFilesServerRouteImport } from './routes/api/sliced-files'
import { ServerRoute as ApiProductsServerRouteImport } from './routes/api/products'
import { ServerRoute as ApiModelsServerRouteImport } from './routes/api/models'
import { ServerRoute as ApiModelCategoriesServerRouteImport } from './routes/api/model-categories'
import { ServerRoute as ApiMetricsServerRouteImport } from './routes/api/metrics'
import { ServerRoute as ApiMaterialTypesServerRouteImport } from './routes/api/material-types'
import { ServerRoute as ApiHealthServerRouteImport } from './routes/api/health'
import { ServerRoute as ApiFilamentsGroupedServerRouteImport } from './routes/api/filaments-grouped'
import { ServerRoute as ApiFilamentsServerRouteImport } from './routes/api/filaments'
import { ServerRoute as ApiFilamentTypesServerRouteImport } from './routes/api/filament-types'
import { ServerRoute as ApiBrandsServerRouteImport } from './routes/api/brands'
import { ServerRoute as ApiFilamentsFilamentIdServerRouteImport } from './routes/api/filaments.$filamentId'
import { ServerRoute as ApiFilamentsFilamentIdModelsServerRouteImport } from './routes/api/filaments.$filamentId.models'

const rootServerRouteImport = createServerRootRoute()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilamentsIndexRoute = FilamentsIndexRouteImport.update({
  id: '/filaments/',
  path: '/filaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlicedFilesServerRoute = ApiSlicedFilesServerRouteImport.update({
  id: '/api/sliced-files',
  path: '/api/sliced-files',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiProductsServerRoute = ApiProductsServerRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiModelsServerRoute = ApiModelsServerRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiModelCategoriesServerRoute =
  ApiModelCategoriesServerRouteImport.update({
    id: '/api/model-categories',
    path: '/api/model-categories',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiMetricsServerRoute = ApiMetricsServerRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMaterialTypesServerRoute = ApiMaterialTypesServerRouteImport.update({
  id: '/api/material-types',
  path: '/api/material-types',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiHealthServerRoute = ApiHealthServerRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiFilamentsGroupedServerRoute =
  ApiFilamentsGroupedServerRouteImport.update({
    id: '/api/filaments-grouped',
    path: '/api/filaments-grouped',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiFilamentsServerRoute = ApiFilamentsServerRouteImport.update({
  id: '/api/filaments',
  path: '/api/filaments',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiFilamentTypesServerRoute = ApiFilamentTypesServerRouteImport.update({
  id: '/api/filament-types',
  path: '/api/filament-types',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiBrandsServerRoute = ApiBrandsServerRouteImport.update({
  id: '/api/brands',
  path: '/api/brands',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiFilamentsFilamentIdServerRoute =
  ApiFilamentsFilamentIdServerRouteImport.update({
    id: '/$filamentId',
    path: '/$filamentId',
    getParentRoute: () => ApiFilamentsServerRoute,
  } as any)
const ApiFilamentsFilamentIdModelsServerRoute =
  ApiFilamentsFilamentIdModelsServerRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => ApiFilamentsFilamentIdServerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/filaments': typeof FilamentsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/models': typeof ModelsIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/filaments': typeof FilamentsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/models': typeof ModelsIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/filaments/': typeof FilamentsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/filaments'
    | '/inventory'
    | '/models'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/filaments' | '/inventory' | '/models' | '/products'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/filaments/'
    | '/inventory/'
    | '/models/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FilamentsIndexRoute: typeof FilamentsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/brands': typeof ApiBrandsServerRoute
  '/api/filament-types': typeof ApiFilamentTypesServerRoute
  '/api/filaments': typeof ApiFilamentsServerRouteWithChildren
  '/api/filaments-grouped': typeof ApiFilamentsGroupedServerRoute
  '/api/health': typeof ApiHealthServerRoute
  '/api/material-types': typeof ApiMaterialTypesServerRoute
  '/api/metrics': typeof ApiMetricsServerRoute
  '/api/model-categories': typeof ApiModelCategoriesServerRoute
  '/api/models': typeof ApiModelsServerRoute
  '/api/products': typeof ApiProductsServerRoute
  '/api/sliced-files': typeof ApiSlicedFilesServerRoute
  '/api/filaments/$filamentId': typeof ApiFilamentsFilamentIdServerRouteWithChildren
  '/api/filaments/$filamentId/models': typeof ApiFilamentsFilamentIdModelsServerRoute
}
export interface FileServerRoutesByTo {
  '/api/brands': typeof ApiBrandsServerRoute
  '/api/filament-types': typeof ApiFilamentTypesServerRoute
  '/api/filaments': typeof ApiFilamentsServerRouteWithChildren
  '/api/filaments-grouped': typeof ApiFilamentsGroupedServerRoute
  '/api/health': typeof ApiHealthServerRoute
  '/api/material-types': typeof ApiMaterialTypesServerRoute
  '/api/metrics': typeof ApiMetricsServerRoute
  '/api/model-categories': typeof ApiModelCategoriesServerRoute
  '/api/models': typeof ApiModelsServerRoute
  '/api/products': typeof ApiProductsServerRoute
  '/api/sliced-files': typeof ApiSlicedFilesServerRoute
  '/api/filaments/$filamentId': typeof ApiFilamentsFilamentIdServerRouteWithChildren
  '/api/filaments/$filamentId/models': typeof ApiFilamentsFilamentIdModelsServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/brands': typeof ApiBrandsServerRoute
  '/api/filament-types': typeof ApiFilamentTypesServerRoute
  '/api/filaments': typeof ApiFilamentsServerRouteWithChildren
  '/api/filaments-grouped': typeof ApiFilamentsGroupedServerRoute
  '/api/health': typeof ApiHealthServerRoute
  '/api/material-types': typeof ApiMaterialTypesServerRoute
  '/api/metrics': typeof ApiMetricsServerRoute
  '/api/model-categories': typeof ApiModelCategoriesServerRoute
  '/api/models': typeof ApiModelsServerRoute
  '/api/products': typeof ApiProductsServerRoute
  '/api/sliced-files': typeof ApiSlicedFilesServerRoute
  '/api/filaments/$filamentId': typeof ApiFilamentsFilamentIdServerRouteWithChildren
  '/api/filaments/$filamentId/models': typeof ApiFilamentsFilamentIdModelsServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/brands'
    | '/api/filament-types'
    | '/api/filaments'
    | '/api/filaments-grouped'
    | '/api/health'
    | '/api/material-types'
    | '/api/metrics'
    | '/api/model-categories'
    | '/api/models'
    | '/api/products'
    | '/api/sliced-files'
    | '/api/filaments/$filamentId'
    | '/api/filaments/$filamentId/models'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/brands'
    | '/api/filament-types'
    | '/api/filaments'
    | '/api/filaments-grouped'
    | '/api/health'
    | '/api/material-types'
    | '/api/metrics'
    | '/api/model-categories'
    | '/api/models'
    | '/api/products'
    | '/api/sliced-files'
    | '/api/filaments/$filamentId'
    | '/api/filaments/$filamentId/models'
  id:
    | '__root__'
    | '/api/brands'
    | '/api/filament-types'
    | '/api/filaments'
    | '/api/filaments-grouped'
    | '/api/health'
    | '/api/material-types'
    | '/api/metrics'
    | '/api/model-categories'
    | '/api/models'
    | '/api/products'
    | '/api/sliced-files'
    | '/api/filaments/$filamentId'
    | '/api/filaments/$filamentId/models'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiBrandsServerRoute: typeof ApiBrandsServerRoute
  ApiFilamentTypesServerRoute: typeof ApiFilamentTypesServerRoute
  ApiFilamentsServerRoute: typeof ApiFilamentsServerRouteWithChildren
  ApiFilamentsGroupedServerRoute: typeof ApiFilamentsGroupedServerRoute
  ApiHealthServerRoute: typeof ApiHealthServerRoute
  ApiMaterialTypesServerRoute: typeof ApiMaterialTypesServerRoute
  ApiMetricsServerRoute: typeof ApiMetricsServerRoute
  ApiModelCategoriesServerRoute: typeof ApiModelCategoriesServerRoute
  ApiModelsServerRoute: typeof ApiModelsServerRoute
  ApiProductsServerRoute: typeof ApiProductsServerRoute
  ApiSlicedFilesServerRoute: typeof ApiSlicedFilesServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filaments/': {
      id: '/filaments/'
      path: '/filaments'
      fullPath: '/filaments'
      preLoaderRoute: typeof FilamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/sliced-files': {
      id: '/api/sliced-files'
      path: '/api/sliced-files'
      fullPath: '/api/sliced-files'
      preLoaderRoute: typeof ApiSlicedFilesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/model-categories': {
      id: '/api/model-categories'
      path: '/api/model-categories'
      fullPath: '/api/model-categories'
      preLoaderRoute: typeof ApiModelCategoriesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/material-types': {
      id: '/api/material-types'
      path: '/api/material-types'
      fullPath: '/api/material-types'
      preLoaderRoute: typeof ApiMaterialTypesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/filaments-grouped': {
      id: '/api/filaments-grouped'
      path: '/api/filaments-grouped'
      fullPath: '/api/filaments-grouped'
      preLoaderRoute: typeof ApiFilamentsGroupedServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/filaments': {
      id: '/api/filaments'
      path: '/api/filaments'
      fullPath: '/api/filaments'
      preLoaderRoute: typeof ApiFilamentsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/filament-types': {
      id: '/api/filament-types'
      path: '/api/filament-types'
      fullPath: '/api/filament-types'
      preLoaderRoute: typeof ApiFilamentTypesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/brands': {
      id: '/api/brands'
      path: '/api/brands'
      fullPath: '/api/brands'
      preLoaderRoute: typeof ApiBrandsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/filaments/$filamentId': {
      id: '/api/filaments/$filamentId'
      path: '/$filamentId'
      fullPath: '/api/filaments/$filamentId'
      preLoaderRoute: typeof ApiFilamentsFilamentIdServerRouteImport
      parentRoute: typeof ApiFilamentsServerRoute
    }
    '/api/filaments/$filamentId/models': {
      id: '/api/filaments/$filamentId/models'
      path: '/models'
      fullPath: '/api/filaments/$filamentId/models'
      preLoaderRoute: typeof ApiFilamentsFilamentIdModelsServerRouteImport
      parentRoute: typeof ApiFilamentsFilamentIdServerRoute
    }
  }
}

interface ApiFilamentsFilamentIdServerRouteChildren {
  ApiFilamentsFilamentIdModelsServerRoute: typeof ApiFilamentsFilamentIdModelsServerRoute
}

const ApiFilamentsFilamentIdServerRouteChildren: ApiFilamentsFilamentIdServerRouteChildren =
  {
    ApiFilamentsFilamentIdModelsServerRoute:
      ApiFilamentsFilamentIdModelsServerRoute,
  }

const ApiFilamentsFilamentIdServerRouteWithChildren =
  ApiFilamentsFilamentIdServerRoute._addFileChildren(
    ApiFilamentsFilamentIdServerRouteChildren,
  )

interface ApiFilamentsServerRouteChildren {
  ApiFilamentsFilamentIdServerRoute: typeof ApiFilamentsFilamentIdServerRouteWithChildren
}

const ApiFilamentsServerRouteChildren: ApiFilamentsServerRouteChildren = {
  ApiFilamentsFilamentIdServerRoute:
    ApiFilamentsFilamentIdServerRouteWithChildren,
}

const ApiFilamentsServerRouteWithChildren =
  ApiFilamentsServerRoute._addFileChildren(ApiFilamentsServerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FilamentsIndexRoute: FilamentsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiBrandsServerRoute: ApiBrandsServerRoute,
  ApiFilamentTypesServerRoute: ApiFilamentTypesServerRoute,
  ApiFilamentsServerRoute: ApiFilamentsServerRouteWithChildren,
  ApiFilamentsGroupedServerRoute: ApiFilamentsGroupedServerRoute,
  ApiHealthServerRoute: ApiHealthServerRoute,
  ApiMaterialTypesServerRoute: ApiMaterialTypesServerRoute,
  ApiMetricsServerRoute: ApiMetricsServerRoute,
  ApiModelCategoriesServerRoute: ApiModelCategoriesServerRoute,
  ApiModelsServerRoute: ApiModelsServerRoute,
  ApiProductsServerRoute: ApiProductsServerRoute,
  ApiSlicedFilesServerRoute: ApiSlicedFilesServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
