name: Deploy to Staging

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.bmad-**/**'
      - '.claude/**'
      - 'scripts/verify-services.sh'
      - 'verify-services.sh'

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Deploy to Cloudflare Workers (Staging)
        run: npm run deploy:staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Set Cloudflare secrets
        run: |
          echo "${{ secrets.JWT_SECRET }}" | npx wrangler secret put JWT_SECRET --env staging
          echo "${{ secrets.BETTER_AUTH_SECRET }}" | npx wrangler secret put BETTER_AUTH_SECRET --env staging
          echo "${{ secrets.DATABASE_URL }}" | npx wrangler secret put DATABASE_URL --env staging
          echo "${{ secrets.SHADOW_DATABASE_URL }}" | npx wrangler secret put SHADOW_DATABASE_URL --env staging
          echo "${{ secrets.RESEND_API_KEY }}" | npx wrangler secret put RESEND_API_KEY --env staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Wait for deployment
        run: sleep 30

      - name: Run staging health check
        run: |
          curl -f https://fm5-staging.solsystemlabs.com/health || exit 1

      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Staging deployment successful"
          echo "URL: https://fm5-staging.solsystemlabs.com"

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Staging deployment failed"
          echo "Check logs for details"
